# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.define "main" do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "public_network", ip: "10.7.0.55"
    config.vm.provision :shell, :path => "bootstrap.sh"
  end
end
